default_stages: [commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-symlinks
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-yaml
    exclude: ".*docker-compose.*|\\.github\\/.*"
    args: [--allow-multiple-documents]
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v5.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional"]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.27.1
  hooks:
    - id: markdownlint
# - repo: https://github.com/IamTheFij/docker-pre-commit
#   rev: v2.0.1
#   hooks:
#     - id: docker-compose-check
#       name: "ensure validity of docker-compose files"
#     - id: hadolint
#       name: "ensure validity of docker files"
