version: "3"
services:
  python-base-alpine:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build python-base-alpine
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/python-base-alpine
    build:
      context: ./base
      dockerfile: alpine.Dockerfile
      args:
        - PYTHON_VERSION=3.9.2
  python-base-debian:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build python-base-debian
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/python-base-debian
    build:
      context: ./base
      dockerfile: debian.Dockerfile
      args:
        - PYTHON_VERSION=3.9.2

  vscode-python-alpine:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build vscode-python-alpine
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/vscode-python-alpine
    build:
      context: ./vscode
      dockerfile: alpine.Dockerfile
      args:
        - USER=code
        - UID=1000
    depends_on:
      - python-base-alpine
  vscode-python-debian:
    # ─────────────────────────────────────────────────────────────────
    # docker-compose -f build.docker-compose.yml build vscode-python-debian
    # ─────────────────────────────────────────────────────────────────
    image: fjolsvin/vscode-python-debian
    build:
      context: ./vscode
      dockerfile: debian.Dockerfile
      args:
        - USER=code
        - UID=1000
    depends_on:
      - python-base-debian
