#!/usr/bin/env bash

# ────────────────────────────────────────────────────────────────────────────────
# Description:  Package manager wrapper script meant to be used in docker files
# Usage:        install-packages <pkg> <pkg>
# ────────────────────────────────────────────────────────────────────────────────

set -o errtrace
set -o functrace
set -o errexit
set -o nounset
set -o pipefail
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
if [[ $EUID -ne 0 ]]; then
   echo >&2 "*** You must run this script as root user." 1>&2
   exit 1
fi
if [ $# = 0 ]; then
  echo >&2 "*** No packages specified"
  exit 1
fi
if [ -n "$(command -v apt-get)" ]; then
  echo >&2 "*** Detected Debian based Linux"
  export RUNLEVEL=1
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -q
  apt-get install -yq --no-install-recommends $@
  sudo apt-get autoremove -y
  apt-get clean -y
  rm -rf \
     /var/cache/debconf/* \
     /var/lib/apt/lists/* \
     /tmp/* \
     /var/tmp/*
fi