#!/usr/bin/env bash
if ! command -v "curl" >/dev/null ; then
  echo >&2 "*** 'curl' was not found in PATH"
  exit 1
fi
if ! command -v "jq" >/dev/null ; then
  echo >&2 "*** 'jq' was not found in PATH"
  exit 1
fi
if ! command -v "wget" >/dev/null ; then
  echo >&2 "*** 'wget' was not found in PATH"
  exit 1
fi
rm -rf /tmp/docker-slim && \
mkdir -p /tmp/docker-slim && \
curl -sL https://api.github.com/repos/docker-slim/docker-slim/releases/latest | jq -r '.tag_name' | xargs -I {} wget -qO /tmp/docker-slim/docker-slim.tar.gz https://downloads.dockerslim.com/releases/{}/dist_linux.tar.gz && \
tar -C /tmp/docker-slim -xvzf /tmp/docker-slim/docker-slim.tar.gz && \
sudo mv -f /tmp/docker-slim/dist_linux/* /usr/local/bin/ && \
rm -r /tmp/docker-slim && \
docker-slim --version
