version: "3"
x-logging-json: &my-logging
  logging:
    driver: json-file
    options:
      max-size: '10M'
      max-file: '5'
services:
  workspace:
    <<: *my-logging
    image: fjolsvin/vscode-alpine:latest
    container_name: workspace
    volumes:
      - ../:/workspace:cached
    command:
      - /bin/sh
      - -cex
      - |
        sudo chown "`id -u`:`id -g`" $$WORKDIR -R ;
        while sleep 1000; do :; done
