version: "3"
services:
  vscode-rust:
    image: vscode-rust
    build:
      context: ./dev
      dockerfile: debian.Dockerfile
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/home/rust/src:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
