name: "docker"
on:
  schedule:
    - cron: "0 0 * * *"
  push:
  workflow_dispatch:
jobs:
  bake:
    defaults:
      run:
        working-directory: ./docker
    name: "build and pushing all docker images"
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: "Login to Docker Container Repository"
        run: echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: "build docker image"
        shell: bash
        run: |
          set -ex ;
          docker buildx use "virtualized-environments" \
          || docker buildx create --use --name "virtualized-environments" --driver docker-container ;
          docker buildx bake --builder virtualized-environments ;
